### PR TITLE
Support Apple M1

### PR DESCRIPTION
**Pull request by xissy**
Trying to make tests possible on Apple M1 machines. Following https://github.com/localstack/localstack/issues/4625#issuecomment-927872700

### CODE REVIEW

**Comment by xissy** [comment]
seems github action workflows not working on this pr. not sure how to make them work. just wanted to be confident that I am not break a thing. :)

**Comment by mingrammer** [comment]
GitHub says `First-time contributors need a maintainer to approve running workflows.`. It seems to be intended.

Could you please roll back the 6ea7bfa commit?

**Comment by xissy** [comment]
> GitHub says `First-time contributors need a maintainer to approve running workflows.`. It seems to be intended.
> 
> Could you please roll back the [6ea7bfa](https://github.com/daangn/kinesumer/commit/6ea7bfa3a38473bc6293e146e56793f79516c3f6) commit?

got it, will do!

**Comment by xissy** [comment]
looks like tests are broken. is it intended or known?

**Comment by mingrammer** [comment]
Broken test codes were fixed.

**Pull request closed without merging**
